2021-12-08 18:35:20.848437: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-12-08 18:35:20.848497: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-12-08 18:35:22.692624: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-08 18:35:22.719880: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2198800000 Hz
2021-12-08 18:35:22.723007: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x16b6c70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-12-08 18:35:22.723043: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-12-08 18:35:22.726549: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-12-08 18:35:24.068327: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x14219c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-12-08 18:35:24.068364: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-DGXS-32GB, Compute Capability 7.0
2021-12-08 18:35:24.068372: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): Tesla V100-DGXS-32GB, Compute Capability 7.0
2021-12-08 18:35:24.068378: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): Tesla V100-DGXS-32GB, Compute Capability 7.0
2021-12-08 18:35:24.068384: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (3): Tesla V100-DGXS-32GB, Compute Capability 7.0
2021-12-08 18:35:24.070583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:07:00.0 name: Tesla V100-DGXS-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.71GiB deviceMemoryBandwidth: 836.37GiB/s
2021-12-08 18:35:24.072096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:08:00.0 name: Tesla V100-DGXS-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.72GiB deviceMemoryBandwidth: 836.37GiB/s
2021-12-08 18:35:24.073567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 2 with properties: 
pciBusID: 0000:0e:00.0 name: Tesla V100-DGXS-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.72GiB deviceMemoryBandwidth: 836.37GiB/s
2021-12-08 18:35:24.075013: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 3 with properties: 
pciBusID: 0000:0f:00.0 name: Tesla V100-DGXS-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.72GiB deviceMemoryBandwidth: 836.37GiB/s
2021-12-08 18:35:24.075141: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-12-08 18:35:24.075225: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory
2021-12-08 18:35:24.075301: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2021-12-08 18:35:24.075377: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2021-12-08 18:35:24.075487: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2021-12-08 18:35:24.075563: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
2021-12-08 18:35:24.079353: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-12-08 18:35:24.079381: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-12-08 18:35:24.079427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-12-08 18:35:24.079439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 2 3 
2021-12-08 18:35:24.079448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N Y Y Y 
2021-12-08 18:35:24.079455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   Y N Y Y 
2021-12-08 18:35:24.079462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 2:   Y Y N Y 
2021-12-08 18:35:24.079469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 3:   Y Y Y N 
WARNING: Logging before flag parsing goes to stderr.
W1208 18:35:25.208872 139729849452352 deprecation.py:506] From /home/yeunglab/.local/lib/python3.6/site-packages/tensorflow/python/training/adagrad.py:77: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W1208 18:35:52.488626 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:36:29.141516 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:37:05.248000 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:37:41.655277 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:38:18.410020 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:38:55.447327 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:39:31.744359 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:40:09.062525 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:40:46.156670 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:41:22.558609 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:41:59.126312 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:42:35.607439 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:43:13.183405 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:43:50.387335 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:44:27.407158 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:45:04.124708 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:45:41.028900 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:46:17.402103 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:46:53.685007 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:47:30.222420 139628256126784 legend.py:1282] No handles with labels found to put in legend.
W1208 18:48:07.438959 139628256126784 legend.py:1282] No handles with labels found to put in legend.
